### ISSUE TITLE
Run before broccoli-asset-rev.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-uglify#1]
Please add the following to `package.json` to ensure it runs _before_ broccoli-asset-rev:

```
"ember-addon": {
  "before": "broccoli-asset-rev"
}
```

**Comment by rwjblue** [comment]
Fixed by https://github.com/jkarsrud/ember-cli-uglify/commit/2b98cf3cdf528951bd06e78a088d1df38257e4ca.

**Comment by jkarsrud** [comment]
Thanks! Forgot to add the issue number in the commit to auto close.
