### ISSUE TITLE
Sequences Break Debugger

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli-uglify#10]
I have some source code that looks like this:

``` js
before();
if (foo) {
  bar();
  baz();
  quux();
}
return after();
```

By default, Uglify will minify that into

``` js
before();
if (foo) bar(), baz(), quux();
return after();
```

That does save a couple characters and it is indeed functionally equivalent.

_However_ if I open up my browser tools (with sourcemap support enabled) and set a break point on `before()`, I get odd behavior. The code stops where it should:

``` js
before(); // <--
if (foo) {
  bar();
  baz();
  quux();
}
return after();
```

When I press "step over," it goes to the `if` and then to `bar()`, as I expect:

``` js
before();
if (foo) {
  bar(); // <--
  baz();
  quux();
}
return after();
```

But now if I press "step over" again, it skips to `after()`. That's because in the actual running code, `bar(), baz(), quux()` is one statement!

The symptom is also described in [A criticism of the Single Var Pattern in JavaScript](http://danhough.com/blog/single-var-pattern-rant/), which suggests this same problem would occur because of `join_vars`.
### The Workaround

In an Ember app, something like

``` js
// ember-cli-build.js:
if (app.env === 'production') {
  app.options.minifyJS.enabled = true;
  app.options.minifyJS.options = {
    compress: { sequences: 0, join_vars: false }
  };
}
```

will turn off `sequences` and `join_vars`.
### Possible Solutions
1. Hope the browsers fix this somehow, possibly by changing "step over" to observe comma-separated statements
2. Have this library set the `sequences` [compressor option](https://github.com/mishoo/UglifyJS2#compressor-options) to 0 by default to prevent converting `;` to `,`
3. Don't change anything, but leave this issue or a wiki or docs page up describing the issue and the workaround
4. Move this issue to [ef4/broccoli-uglify-sourcemap](https://github.com/ef4/broccoli-uglify-sourcemap)

**Comment by ef4** [comment]
I think the existing browser behavior is correct. There are lots of ways to make a compound statement, and generally "step over" is supposed to skip over all of them and take you to the next statement. The alternative is to stop at every expression, which means hitting "step over" multiple times to get past something like `x = a() + b()`, which can rapidly get annoying.

It is unfortunate that sourcemapping can't reverse this transformation. What you really want is to step to the next statement _in the original source_, not the compressed source. But that's not really possible given how the sourcemap specs works -- the original source might not even be Javascript, and there's no specced way of denoting where its statement boundaries are.

How big an impact does `sequences: 0` have on the size of a real Ember app?

**Comment by jamesarosen** [comment]
> How big an impact does sequences: 0 have on the size of a real Ember app?

For my `app.js`, the default (`sequences: 200`) yields 1,882,864B, while `compress: { sequences: 0 }`: yields 1,883,078B. That's an increase of 214B or about 0.01%.

Setting `compress: { sequences: 0, join_vars: false }` yields 1,897,526B. That's an increase over the original of 14,662B or about 0.78%.

**Comment by mike-north** [comment]
I'm seeing less than 1KB as well `1,441,017` --> `1,441,268` for Δ251B, using the same constraints as @jamesarosen

**Comment by jamesarosen** [comment]
Another option would be more of a ​_forced-choice_​: don't have ef4/broccoli-uglify-sourcemap or ember-cli/ember-cli-uglify form an opinion, but ​_generate_​ an opinion in the `ember-cli-build.js. That is, add

``` js
app.options.minifyJS.options = {
  compress: {
    sequences: 0,
    join_vars: false
  }
};
```

in the [blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/ember-cli-build.js).

**Comment by ef4** [comment]
Seems like the debugging cost isn't worth the size improvement. I'd be OK with making `sequences:0` the default.

**Comment by rwjblue** [comment]
Seems good to me also.

**Comment by stefanpenner** [comment]
sequences are configurable + newer versions of chrome allow for mid-expression breakpoints. I think we can close this.
