### ISSUE TITLE
Unable to uglify ES6 code

### ISSUE THREAD

**Issue by Polve** [ember-cli/ember-cli-uglify#14]
I'm importing with browserify some modules that use ES6 syntax and uglify fails with a big stack call dump.

Is there some workaround for this problem?

This can be related to https://github.com/ef4/ember-browserify/issues/97

**Comment by ghost** [comment]
+1. this is mysteriously breaking my `ember build` runs when importing an external file that contains ES6. Underlying issue seems to already be reported: https://github.com/mishoo/UglifyJS2/issues/448

**Comment by fusion2004** [comment]
I forked this & the associated broccoli plugin and got it working with the recently released [uglify-es](https://www.npmjs.com/package/uglify-es) package here:
https://github.com/fusion2004/ember-cli-uglify-es
https://github.com/fusion2004/broccoli-uglify-es-sourcemap

I'm not 100% of the output of the sourcemaps, I mostly changed them to match the new outputs.
Would a PR to bring my changes upstream be welcome for consideration?

**Comment by Polve** [comment]
@fusion2004 
I tried deleting ember-cli-uglify and depending instead by ember-cli-uglify-es but it does not work for me: it still pulls uglify-js instead of uglify-es and the build fails with the usual error.

**Comment by rwjblue** [comment]
> Would a PR to bring my changes upstream be welcome for consideration?

@fusion2004 - Yes, please!

**Comment by Turbo87** [comment]
resolved by `v2.0.0`
