### ISSUE TITLE
broccoli-uglify-sourcemap dependency needs to be updated

### ISSUE THREAD

**Issue by ctwoolsey** [ember-cli/ember-cli-uglify#201]
dependency for "broccoli-uglify-sourcemap" needs to be updated to "3.2.0" as this version uses a dependency of  "terser": "^4.6.13",

The current dependency of "broccoli-uglify-sourcemap" causes terser 4.6.8 to be used and this has a breaking bug: [https://github.com/terser/terser/issues/625](url)

**Comment by rwjblue** [comment]
This is just a lockfile issue, we already allow `4.6.13` with the current versions. I'd suggest that you remove `ember-cli-uglify` from your package.json, run `npm install` / `yarn`, add it back, then run `npm install` / `yarn` to ensure your lockfile gets updated with the latest version.

**Comment by ctwoolsey** [comment]
OK, thank you, i will do that.
