### ISSUE TITLE
2.0.0-beta.1 compile times

### ISSUE THREAD

**Issue by koryteg** [ember-cli/ember-cli-uglify#23]
my `vendor.js` seems to be taking 50 seconds on every files save when switching to the latest beta. 

![screen shot 2017-07-14 at 5 14 00 pm](https://user-images.githubusercontent.com/777967/28251372-89eb2d2a-6a30-11e7-8459-ab02598ec936.png)

my `config/targets.js` file looks like this as well:

``` javascript
var ENV = {
  browsers: [
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```
just thought I would bring this up incase you haven't noticed a significant slowdown.

**Comment by rwjblue** [comment]
What was it before? Why are you running with uglification on for normal development (genrally only on in prod)?

**Comment by rwjblue** [comment]
@koryteg - Ping?

**Comment by koryteg** [comment]
hey sorry, been a long week.
after thinking about this a bit more. I realized, I am not sure I have all the correct data needed to make sure there was a slowdown, and not sure this really matters, I am not and don't know anyone who is using uglify in development.

here is the data I have though:
I cant really run a test 1 to 1, because the app doesn't compile when only targeting latest browsers and using `1.2.0`.

but while targeting latest browsers plus `ie 9`  using `ember-cli-uglify-1.2.0`, I am getting about 1m07s for initial compile times and then about 21s for updates. `2.0.0-beta1` targeting only latests was taking about 50s on initial as well as updates.

**Comment by rwjblue** [comment]
To recap: initial builds seem a bit faster (goes from 67s for 1.2.0 down to 50s for 2.0.0-beta.1), but rebuilds in 2.0.0-beta.x have no savings vs initial builds (e.g. rebuilds in 2.0.0-beta.1 take the same amount of time as initial builds).

@koryteg - Is that a good summary?

**Comment by koryteg** [comment]
yes that is correct.

**Comment by bertdeblock** [comment]
Going to close as this issue seems outdated.
