### ISSUE TITLE
v2.0.0-beta.1 broken on Safari

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/ember-cli-uglify#25]
Builds that are uglified with v2.0.0-beta.1 will break in safari with the error `SyntaxError: Cannot declare a let variable twice: 't'.`

This is actually a bug in safari Version 10 and it is fixed in Technology Preview (Release 37 (Safari 11.1, WebKit 12605.1.2). 

This issues was reported upstream in UglifyJS2:
https://github.com/mishoo/UglifyJS2/issues/1753

I don't believe there is anything for ember-cli-uglify to do here except wait. I'm only opening an issue so beta.1 doesn't become final with a breaking change in a major browser and as a reference for anyone else trying out the beta.

**Comment by rwjblue** [comment]
See https://github.com/glimmerjs/glimmer-blueprint/issues/58.  I think we can update the defaults here, to be compatible...

**Comment by ghost** [comment]
I'm on latest everything (ember, ember-data, with this targets.js:

browsers: [
    'last 2 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions',
    'last 1 Edge versions'
  ]

with `"ember-cli-uglify": "2.0.0-beta.1"` and with Safari iOS 10.3.3 (latest) everything works in Safari (and Chrome of course) and on my MacOS Sierra 10.12.5 with Safari (default) and Technology Preview.

Everything good. Why the issue?

**UPDATE**:

Maybe I'm wrong, but switching from ember-data 2.14.x to 2.13.2 create this problem. I will confirm later.

**Comment by ghost** [comment]
I can confirm.

Ember-data 2.14.x fix the problem. ~2.13.2 is broken.
