### ISSUE TITLE
Ember build is falling in production environment

### ISSUE THREAD

**Issue by devdemi** [ember-cli/ember-cli-uglify#271]
After the new release of `Terser` - `5.7.0` ember build starts to fall with the message:
`Unexpected token punc «:», expected punc «,»`
Here the log:
https://gist.github.com/devdemi/0179b3f827f2edb2a14a7607be96b56d
Please give me advice on how to find out where is a problem in my code because there is stack trace of ember inside in log file.

**Comment by mabab** [comment]
Hi, I have a problem too, I created the demo: [https://github.com/mabab/bug-ember-terser](https://github.com/mabab/bug-ember-terser) . 

```npx ember server -prod --port 4201```

it seems this problem through quotes ``
``` console.log(`/assets/assetMap.json`); ```

[https://gist.github.com/mabab/991b1ce63c1a784b49185f287e4ad9d9](https://gist.github.com/mabab/991b1ce63c1a784b49185f287e4ad9d9)


In Ember 3.26 I got an error too

**Comment by mabab** [comment]
it is not related to this package.
the problem is reproduced here: https://github.com/ember-cli/ember-cli/issues/9528

**Comment by bertdeblock** [comment]
Is this issue still relevant?
