### ISSUE TITLE
Failed to open file /code_cache/.overlay/base.apk/assets/Mapnik/7/90/51.png

### ISSUE THREAD

**Issue by sumit-dahiya19** [ember-cli/ember-cli-uglify#290]
E/projectName.ProjectBuild: Failed to open file '/data/data/com.pojectName.projectBuild/code_cache/.overlay/base.apk/assets/Mapnik/7/90/51.png': No such file or directory

**Comment by Muhammad-ruman** [comment]
I am having same problem

2021-12-16 14:51:21.660 31402-31402/com.ribedevs.buildup E/ibedevs.buildu: Failed to open file '/data/data/com.ribedevs.buildup/code_cache/.overlay/base.apk/resources.arsc': No such file or directory

how do I fix it ????

**Comment by imeeran** [comment]
How did you fix that?
I have also same error

**Comment by devIbtihadj** [comment]
same error

**Comment by massimilianochiodi** [comment]
Same error

**Comment by Peppo10** [comment]
same error Failed to open file '/data/data/it.uniba.dib.sms222334/code_cache/.overlay/base.apk/res/layout/veterinarian_profile_fragment.xml': No such file or directory

**Comment by DaifMX** [comment]
I had the same problem, updating the IDE and re-syncing the gradle project fixed my issue. Hope it helps.
