### ISSUE TITLE
Mark `ember-cli-uglify` package as deprecated

### ISSUE THREAD

**Issue by bmish** [ember-cli/ember-cli-uglify#301]
```
npm deprecate ember-cli-uglify "Renamed to ember-cli-terser."
```

Increase visibility that the package with the old name is deprecated/renamed.
* https://www.npmjs.com/package/ember-cli-uglify
* https://github.com/ember-cli/ember-cli-terser/pull/230

**Comment by Turbo87** [comment]
done ✅
