### ISSUE TITLE
Ember cli sourcemaps setting not respected by 4.0.2?

### ISSUE THREAD

**Issue by MiikaH** [ember-cli/ember-cli-uglify#306]
Unlike the documentation claims, ember-cli-terser seems to generate sourcemaps even for production builds regardless of how the ember-cli sourcemaps setting is configured.

Only way to disable sourcemaps from what I can tell is explicitly set `'ember-cli-terser'.terser.sourceMap = false`

**Comment by bertdeblock** [comment]
@MiikaH If this issue is still relevant to you, would you mind testing out #313?

**Comment by EWhite613** [comment]
When will this fix be released @bertdeblock? Looks like it hasn't been released in 2 years

**Comment by EWhite613** [comment]
Even if I am explicitly disabling for terser, it still looks like it's producing sourcemaps. Whereas previously using `ember-cli-uglify` didn't have this problem
```
    'ember-cli-terser': {
      terser: {
        compress: {
          collapse_vars: false
        },
        sourceMap: false
      }
    },
```
