### ISSUE TITLE
Update README that minifyJS is dropped

### ISSUE THREAD

**Issue by GCheung55** [ember-cli/ember-cli-uglify#31]
Since `minifyJS` was dropped from the options, it would be helpful to add that to the README as part of some upgrade notice.

**Comment by courthead** [comment]
Agreed, just upgraded Ember and was lucky to notice on my own that my files were no longer minified after deploying to staging, then had to do some digging to find out why. Could've easily not noticed and ended up deploying much bigger files to production. IMO there should be at least a warning, not just a README update.

**Comment by jelhan** [comment]
Updating new ember cli guides: https://github.com/ember-learn/cli-guides/pull/70

**Comment by rwjblue** [comment]
Closing for now, sorry this caused trouble for folks 😞
