### ISSUE TITLE
"a51329 is not defined" when running `ember s -prod`

### ISSUE THREAD

**Issue by jzisser9** [ember-cli/ember-cli-uglify#33]
Hi there,
I believe this might be related to the other sourcemap issues reported already, but I wanted to bring up our own issue we're running into since upgrading `ember-cli-uglify` to v2.0.0 from v1.2.0: When trying to visit any page in our ember app started up using `ember s -prod`, we get the following error in the console and nothing is rendered on-page: `a51329 is not defined`.

It seems like part of one of our ember addons (ember-data) got mangled after it was minified, as a few of the lines in the stack trace are functionally-different than the actual code in the addon's source code.

**Comment by rwjblue** [comment]
This is an issue with uglify-es. It has been fixed but is pending release I believe. Please review upstream issues for details.
