### ISSUE TITLE
Ember build development must compress js files the same as production

### ISSUE THREAD

**Issue by christopherbecker** [ember-cli/ember-cli-uglify#95]
I have two environments.
Production and development.

Development is slow because the vendor file is 2mb and on production it is 500kb. I need development to build the same as production.

I've tried everything I could find, also setting my environment as production won't work because then my Ember app will point to  production API and not development.

For example: 
`ember s` should minify the same as `ember s -prod`

Thank you in advance.

**Comment by Turbo87** [comment]
you can set `enabled: true` as described in the README file. I don't see how development could possibly be faster by enabling minification though...
